t: t.o soi.o soi.h
	cc t.o soi.o -o t

t.o: t.c
	cc -c t.c -o t.o


w: w.o soi.o soi.h
	cc w.o soi.o -o w

w.o: w.c
	cc -c w.c -o w.o 


x: x.c
	cc x.c -o x

soi.o: soi.c soi.h
	cc -c soi.c -o soi.o
	
